### ISSUE TITLE
Domain Values

### ISSUE THREAD

**Issue by ColinSchut** [ytgov/spatial-data-dictionary#10]
Looks like domains have been started. In the GIS at least the values come in pairs, a Code (the value actually entered into the field) and a Definition (the text displayed in the field). I think we'll need to be able to enter in both separately; in one tag we'd need a standard format to capture that.

Codes can also be ranges of values, but the same formatting should work for both types. 

![image](https://user-images.githubusercontent.com/43657239/109076874-33049180-76f3-11eb-8daa-e7cc0092685f.png)

**Comment by datajohnson** [comment]
Added Values tab
