### ISSUE TITLE
Permissions, Programs, and People - Mar 3rd Weekly Call

### ISSUE THREAD

**Issue by tleongbe** [ytgov/spatial-data-dictionary#15]
For the permissions, we should consider the linkages between Programs and People. 

Programs should have "Managers" who would then be Data Stewards for any entities tagged with that program. The "Program Manager" should be listed in the Programs tab. 

People should be able to "subscribe" to a program to receive notifications of upcoming changes. These changes are initiated one of two ways:
1.    A person with read access **requests/proposes a change** (entering the changes as if they had edit access, though the changes do not yet occur) and this request is routed through an approval process based on who the data steward(s) is/are and who has edit access. If the change is approved, any people subscribed to the entities program will receive a notification of the upcoming change. 
2.    A person with edit access **makes a change**, and this request is routed through an approval process to the data steward(s). If the change is approved, any people subscribed to the entities program will receive a notification of the upcoming change. 

**People Tab** 
We should ensure to track the following:
- Name
- Position
- Branch
- Unit
- Email
- Status (Active/Inactive)
- Programs Subscribed to

**Comment by datajohnson** [comment]
Done
