### ISSUE TITLE
Workspaces

### ISSUE THREAD

**Issue by ColinSchut** [ytgov/spatial-data-dictionary#8]
I do think that being able to visualize/search/navigate by workspace is useful, and should be a more structured thing than a custom  property of an entity. Maybe just defining certain types of properties such as "workspace" and "status" that have options in a drop down list. I can see myself wanting to see search for my draft entities for instance. 

Also, multiple entities will share the same name, so some way to differentiate them at a glance. Automatically adding workspace name to entity name?

**Comment by datajohnson** [comment]
@ColinSchut  I agree with you that a more structured hierarchy would be helpful. I'm not a huge fan of the term "Workspace" because I think it may bring other ideas with it. What do you think about "Program" or "Group" or "Section" or "Class" maybe?

**Comment by datajohnson** [comment]
@ColinSchut I also think I'm going to add a "Location" field, which like I mentioned in the meeting, could be either a database, file, web service, etc. When you talked about having multiple entities with the same names, what fields do you want to use to uniquely identity one?

**Comment by ColinSchut** [comment]
For the 

> @ColinSchut I also think I'm going to add a "Location" field, which like I mentioned in the meeting, could be either a database, file, web service, etc. When you talked about having multiple entities with the same names, what fields do you want to use to uniquely identity one?

I think "Location" could work, I'm going to think if there are any situations where it wouldn't. 

Tough to say, the location could be the only distinguishing thing about them.  They could be identical copies, simply located in different databases.

**Comment by ColinSchut** [comment]
> @ColinSchut I agree with you that a more structured hierarchy would be helpful. I'm not a huge fan of the term "Workspace" because I think it may bring other ideas with it. What do you think about "Program" or "Group" or "Section" or "Class" maybe?

If you're referring to asset class or the program area responsible then I think "Program" is probably best. I think it can cover "program areas" which asset classes are considered to be but also more general work units. I

**Comment by kljeffre** [comment]
As work units evolve over time I think it might be better to use "Asset Class" as opposed to "Program". It also eliminates the confusion that might come from thinking of software programs...which is where my thoughts went first when I saw that.

**Comment by ColinSchut** [comment]
> As work units evolve over time I think it might be better to use "Asset Class" as opposed to "Program". It also eliminates the confusion that might come from thinking of software programs...which is where my thoughts went first when I saw that.

I think we should discuss exactly how we want to use that information in the software. For me, I was thinking I would also use it for things like units within branches. For example, Geotech, or Traffic Engineering.

**Comment by datajohnson** [comment]
I think this is covered ( can address in later phases if required )
